version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:18.4.0-xe
    container_name: oracle-db
    environment:
      - ORACLE_PWD=MinhaSenhaSegura123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  api-java:
    build:
      context: ./api-java
    container_name: api-java
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=MinhaSenhaSegura123
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    restart: unless-stopped

volumes:
  oracle-data: